site_name: R1B(ot) Docs

theme:
  name: material
  palette: 
    primary: teal # Change to your preferred color
    accent: purple
  features:
    - navigation.tabs # Top navigation bar
    - navigation.sections
    - content.code.copy # Copy button for code blocks

markdown_extensions:
  - admonition # Info/Warning boxes
  - pymdownx.highlight: # Better code highlighting
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences: # Allows diagrams (Mermaid)
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # LaTeX support for math
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
